library(dplyr)
library(ggplot2)

# Use the motif table (html file) generated by Seqpos motif to generate as csv file by copying the motif (labelled as factor) and their z scores
#read the csv table
AR_motifs <- read.csv("/Users/prakashsah/stelloo_fig2/data/AR/AR_motifs.csv")

# Select top motifs
top_motifs <- AR_motifs %>%
  dplyr::slice(1:10)

# Plot
ggplot(top_motifs, aes(x = reorder(factor, zscore), y = zscore)) +
  geom_col(fill = "darkgrey") +
  labs(
    title = "Top motifs at AR binding sites", 
    x = "Motif", 
    y = "Z-score"
  ) +
  theme_minimal(base_size = 15) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

